"""Platform Core package providing base primitives and standard exceptions."""

from platform_core.errors import (
    AuthenticationError,
    AuthorizationError,
    ConfigurationError,
    DataSanitizationError,
    DomainValidationError,
    IntegrationConnectionError,
    IntegrationError,
    PlatformError,
    ProtocolViolationError,
    RateLimitExceededError,
    ResourceNotFoundError,
    SecurityError,
    TimeoutError,
    ValidationError,
)
from platform_core.models import (
    AuditMetadata,
    CorrelationIdentifier,
    PageRequest,
    PageResponse,
    PlatformBaseModel,
    PrincipalIdentity,
    UtcTimestamp,
)

__all__ = [
    "AuditMetadata",
    "AuthenticationError",
    "AuthorizationError",
    "ConfigurationError",
    "CorrelationIdentifier",
    "DataSanitizationError",
    "DomainValidationError",
    "IntegrationConnectionError",
    "IntegrationError",
    "PageRequest",
    "PageResponse",
    "PlatformBaseModel",
    "PlatformError",
    "PrincipalIdentity",
    "ProtocolViolationError",
    "RateLimitExceededError",
    "ResourceNotFoundError",
    "SecurityError",
    "TimeoutError",
    "UtcTimestamp",
    "ValidationError",
]
